services:
  payload_camera:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: payload_camera_ws:iron
    container_name: payload_camera_ws
    # Needed for libcamera / v4l2 camera access
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    environment:
      - ROS_DOMAIN_ID=0
    network_mode: host
    stdin_open: true
    tty: true
