name: Run All Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          docker build -f docker/Dockerfile -t payload_camera_ws:iron .

      - name: Run tests
        run: |
          docker run --rm payload_camera_ws:iron bash /payload_camera_ws/docker/run_tests.sh
